---
- name: Restart Hostd and Vpxa services
  hosts: all
  tasks:


     - name: VMware version info
       command: uname -r
       register: test

     - debug:
        var: "{{ test | to_nice_json }}"

     - name: Change file
       lineinfile: dest=/etc/hosts line="couchbase.host=127.0.0.1"
       register: test1

     - debug:
        var: "{{ test1 | to_nice_json }}"

